/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddProductModal: typeof import('./components/pop-up/AddProductModal.vue')['default']
    AdminSideBar: typeof import('./components/AdminSideBar.vue')['default']
    CustomerFooter: typeof import('./components/CustomerFooter.vue')['default']
    CustomerNavBar: typeof import('./components/CustomerNavBar.vue')['default']
    FilterSideBar: typeof import('./components/FilterSideBar.vue')['default']
    FloatingWhatsAppButton: typeof import('./components/FloatingWhatsAppButton.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    NavButton: typeof import('./components/NavButton.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    ProductCard: typeof import('./components/ProductCard.vue')['default']
    ProductList: typeof import('./components/ProductList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
  }
}
