/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/halaman-utama': RouteRecordInfo<'/admin/halaman-utama', '/admin/halaman-utama', Record<never, never>, Record<never, never>>,
    '/admin/informasi-kontak': RouteRecordInfo<'/admin/informasi-kontak', '/admin/informasi-kontak', Record<never, never>, Record<never, never>>,
    '/admin/katalog-produk': RouteRecordInfo<'/admin/katalog-produk', '/admin/katalog-produk', Record<never, never>, Record<never, never>>,
    '/admin/kategori': RouteRecordInfo<'/admin/kategori', '/admin/kategori', Record<never, never>, Record<never, never>>,
    '/admin/login': RouteRecordInfo<'/admin/login', '/admin/login', Record<never, never>, Record<never, never>>,
    '/admin/tentang-kami': RouteRecordInfo<'/admin/tentang-kami', '/admin/tentang-kami', Record<never, never>, Record<never, never>>,
    '/tentang-kami': RouteRecordInfo<'/tentang-kami', '/tentang-kami', Record<never, never>, Record<never, never>>,
  }
}
