/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/home/Banner': RouteRecordInfo<'/home/Banner', '/home/Banner', Record<never, never>, Record<never, never>>,
    '/home/Pencapaian': RouteRecordInfo<'/home/Pencapaian', '/home/Pencapaian', Record<never, never>, Record<never, never>>,
    '/home/ProdukAndalan': RouteRecordInfo<'/home/ProdukAndalan', '/home/ProdukAndalan', Record<never, never>, Record<never, never>>,
    '/KatalogProduk': RouteRecordInfo<'/KatalogProduk', '/KatalogProduk', Record<never, never>, Record<never, never>>,
    '/TentangKami': RouteRecordInfo<'/TentangKami', '/TentangKami', Record<never, never>, Record<never, never>>,
  }
}
